// <auto-generated />
using System;
using Blog.Data.Concrete.EFCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog.Data.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20220226190352_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog.Entities.Concrete.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeoAuthor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SeoTags")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CommentCount = 1,
                            Content = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(8193),
                            Date = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(7457),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(8563),
                            Note = "C# 9.0 ve .NET 5 Yenilikleri",
                            SeoAuthor = "Mehmet GÖN",
                            SeoDescription = "C# 9.0 ve .NET 5 Yenilikleri",
                            SeoTags = "C#,C# 9, .NET 5, .NET Framework, .NET Core",
                            Thumbnail = "Default.jpg",
                            Title = "C# 9.0 ve .NET 5 Yenilikleri",
                            UserId = 1,
                            ViewsCount = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CommentCount = 1,
                            Content = "Yinelenen bir sayfa içeriğinin okuyucunun dikkatini dağıttığı bilinen bir gerçektir. Lorem Ipsum kullanmanın amacı, sürekli 'buraya metin gelecek, buraya metin gelecek' yazmaya kıyasla daha dengeli bir harf dağılımı sağlayarak okunurluğu artırmasıdır. Şu anda birçok masaüstü yayıncılık paketi ve web sayfa düzenleyicisi, varsayılan mıgır metinler olarak Lorem Ipsum kullanmaktadır. Ayrıca arama motorlarında 'lorem ipsum' anahtar sözcükleri ile arama yapıldığında henüz tasarım aşamasında olan çok sayıda site listelenir. Yıllar içinde, bazen kazara, bazen bilinçli olarak (örneğin mizah katılarak), çeşitli sürümleri geliştirilmiştir.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9362),
                            Date = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9360),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9363),
                            Note = "C++ 11 ve 19 Yenilikleri",
                            SeoAuthor = "Mehmet GÖN",
                            SeoDescription = "C++ 11 ve 19 Yenilikleri",
                            SeoTags = "C++ 11, C++ 19, C++ Yenilikleri",
                            Thumbnail = "Default.jpg",
                            Title = "C++ 11 ve 19 Yenilikleri",
                            UserId = 2,
                            ViewsCount = 300
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CommentCount = 1,
                            Content = "Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan de Finibus Bonorum et Malorum (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan Lorem ipsum dolor sit amet 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9369),
                            Date = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9368),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9371),
                            Note = "JavaScript Yenilikleri",
                            SeoAuthor = "Mehmet GÖN",
                            SeoDescription = "JavaScript Yenilikleri",
                            SeoTags = "JavaScript Yenilikleri,Modern JavaScript,JavaScript,ES2019,ES2020",
                            Thumbnail = "Default.jpg",
                            Title = "JavaScript ES2019 ve ES2020 Yenilikleri",
                            UserId = 3,
                            ViewsCount = 258
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CommentCount = 1,
                            Content = "Lorem Ipsum pasajlarının birçok çeşitlemesi vardır. Ancak bunların büyük bir çoğunluğu mizah katılarak veya rastgele sözcükler eklenerek değiştirilmişlerdir. Eğer bir Lorem Ipsum pasajı kullanacaksanız, metin aralarına utandırıcı sözcükler gizlenmediğinden emin olmanız gerekir. İnternet'teki tüm Lorem Ipsum üreteçleri önceden belirlenmiş metin bloklarını yineler. Bu da, bu üreteci İnternet üzerindeki gerçek Lorem Ipsum üreteci yapar. Bu üreteç, 200'den fazla Latince sözcük ve onlara ait cümle yapılarını içeren bir sözlük kullanır. Bu nedenle, üretilen Lorem Ipsum metinleri yinelemelerden, mizahtan ve karakteristik olmayan sözcüklerden uzaktır.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9376),
                            Date = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9375),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9378),
                            Note = "Pyton Yenilikleri",
                            SeoAuthor = "Mehmet GÖN",
                            SeoDescription = "Pyton Yenilikleri",
                            SeoTags = "Pyton Yenilikleri,Modern Pyton,Pyton",
                            Thumbnail = "Default.jpg",
                            Title = "Pyton Yenilikleri",
                            UserId = 4,
                            ViewsCount = 521
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CommentCount = 1,
                            Content = "Lorem Ipsum pasajlarının birçok çeşitlemesi vardır. Ancak bunların büyük bir çoğunluğu mizah katılarak veya rastgele sözcükler eklenerek değiştirilmişlerdir. Eğer bir Lorem Ipsum pasajı kullanacaksanız, metin aralarına utandırıcı sözcükler gizlenmediğinden emin olmanız gerekir. İnternet'teki tüm Lorem Ipsum üreteçleri önceden belirlenmiş metin bloklarını yineler. Bu da, bu üreteci İnternet üzerindeki gerçek Lorem Ipsum üreteci yapar. Bu üreteç, 200'den fazla Latince sözcük ve onlara ait cümle yapılarını içeren bir sözlük kullanır. Bu nedenle, üretilen Lorem Ipsum metinleri yinelemelerden, mizahtan ve karakteristik olmayan sözcüklerden uzaktır.",
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9385),
                            Date = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9384),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 964, DateTimeKind.Local).AddTicks(9387),
                            Note = "Asp.net Yenilikleri",
                            SeoAuthor = "Mehmet GÖN",
                            SeoDescription = "Asp.net Yenilikleri",
                            SeoTags = "Asp.net Yenilikleri,Modern Asp.net,Asp.net",
                            Thumbnail = "Default.jpg",
                            Title = "Asp.net Yenilikleri",
                            UserId = 1,
                            ViewsCount = 346
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4927),
                            Description = "C# Programlama Dili İLe İlgili En Güncel Bilgiler",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4936),
                            Name = "C#",
                            Note = "C# Blog Kategorisi"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4945),
                            Description = "C++ Programlama Dili İLe İlgili En Güncel Bilgiler",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4946),
                            Name = "C++",
                            Note = "C++ Blog Kategorisi"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4950),
                            Description = "JavaScript Programlama Dili İLe İlgili En Güncel Bilgiler",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4951),
                            Name = "JavaScript",
                            Note = "JavaScript Blog Kategorisi"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4955),
                            Description = "Pyton Programlama Dili İLe İlgili En Güncel Bilgiler",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4957),
                            Name = "Pyton",
                            Note = "Pyton Blog Kategorisi"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4961),
                            Description = "Kotlin Programlama Dili İLe İlgili En Güncel Bilgiler",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4962),
                            Name = "Kotlin",
                            Note = "Kotlin Blog Kategorisi"
                        },
                        new
                        {
                            Id = 6,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4966),
                            Description = "Asp.Net Programlama Dili İLe İlgili En Güncel Bilgiler",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 967, DateTimeKind.Local).AddTicks(4968),
                            Name = "Asp.Net",
                            Note = "Asp.Net Blog Kategorisi"
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2251),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2260),
                            Note = "C# Makale Yorumu",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed urna enim, lacinia porttitor egestas et, interdum et risus. Integer tincidunt tempus rutrum. Duis tristique tortor tellus, quis rhoncus nulla sollicitudin at. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam in odio dictum, tempus eros sit amet, fringilla justo. Maecenas eu arcu tortor. Donec congue massa a placerat varius. Cras felis dolor, cursus et ullamcorper vitae, fermentum a nisl. Aliquam erat volutpat."
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2272),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2274),
                            Note = "C++ Makale Yorumu",
                            Text = "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla aliquam leo nisl, ac tempus velit volutpat sed. Mauris mattis tellus non lobortis viverra. Etiam a efficitur nisl. Curabitur id accumsan sem. Suspendisse potenti. Nam luctus tempor nisi, quis elementum magna sodales sit amet. Curabitur vel rutrum urna. Mauris felis purus, tempor vitae congue vel, rutrum eu magna. Nullam pulvinar, arcu sit amet euismod tincidunt, leo lorem dictum turpis, eget tristique nunc dui vel sem."
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2348),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2349),
                            Note = "JavaScript Makale Yorumu",
                            Text = "Nulla facilisi. Vestibulum eget porta lorem, ac placerat nibh. Nullam lectus massa, consequat et ligula eget, interdum hendrerit lectus. Sed varius tincidunt ligula, vel tempus lacus sollicitudin fringilla. Donec in commodo risus. Maecenas ornare eros vitae metus posuere congue. Pellentesque tincidunt vulputate malesuada."
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 4,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2354),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2355),
                            Note = "Pyton Makale Yorumu",
                            Text = "Vestibulum at porta orci. Aenean efficitur justo elit, ut dictum erat lobortis eu. Donec lacinia nibh turpis, sed blandit massa mattis vitae. Sed ex justo, pellentesque in tellus eget, rhoncus venenatis nibh. Cras feugiat nibh enim, et pulvinar quam feugiat et. Morbi ut tellus a mauris dapibus pharetra pharetra at metus. Aenean magna nisl, sodales sed dignissim in, dapibus eu mauris. In cursus magna vitae est accumsan pretium. Donec vitae dui nisi. Cras in risus nec turpis fringilla \"imperdiet\" vel et purus. Integer tristique vitae nunc laoreet porttitor. Sed arcu nisi, feugiat eget vulputate eget, tempus sed turpis. Sed ac ligula in odio pretium dignissim ut a ligula. Praesent mattis et neque at rhoncus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam non magna vestibulum, posuere ante eget, tempus odio."
                        },
                        new
                        {
                            Id = 5,
                            ArticleId = 5,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2359),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 981, DateTimeKind.Local).AddTicks(2361),
                            Note = "Asp.net Makale Yorumu",
                            Text = "Donec ex erat, varius vitae arcu ac, euismod sagittis lectus. Fusce feugiat quam in dui malesuada, in tincidunt nunc tincidunt. Mauris ultrices ligula sit amet laoreet feugiat. Nulla laoreet rutrum libero, sit amet lobortis leo. Aenean posuere ipsum condimentum lacus faucibus, at tempor metus cursus. Aenean mauris nibh, volutpat id ultrices id, varius ut magna. Donec a ligula sed eros vestibulum porta sit amet et leo. Pellentesque eu orci lectus. Aenean semper vitae nisl quis semper. Suspendisse in nunc lacus. Vestibulum volutpat lectus tellus, sed sollicitudin felis elementum non. Aenean malesuada congue orci sed placerat. Nullam feugiat tellus sit amet tellus accumsan fermentum. Vestibulum euismod, nisl eu porttitor rhoncus, ligula metus hendrerit est, at blandit augue massa quis ante. Morbi ac mi at lectus fringilla bibendum."
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripton")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 979, DateTimeKind.Local).AddTicks(3438),
                            Descripton = "Tüm Haklara Sahiptir",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 979, DateTimeKind.Local).AddTicks(3447),
                            Name = "Admin",
                            Note = "Admin Rolüdür"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 979, DateTimeKind.Local).AddTicks(3459),
                            Descripton = "Admin Kadar Olmasada Var Biraz Hakkı işte",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 979, DateTimeKind.Local).AddTicks(3461),
                            Name = "Moderatör",
                            Note = "Moderatör Rolüdür"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 979, DateTimeKind.Local).AddTicks(3465),
                            Descripton = "Hiç Hakka Sahip Değildir. Öyle Arada Gelir Gider.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 979, DateTimeKind.Local).AddTicks(3466),
                            Name = "User",
                            Note = "User Rolsüzlüğüdür"
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descreption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARBINARY(500)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 977, DateTimeKind.Local).AddTicks(6802),
                            Descreption = "Bu Programın Yazarı",
                            Email = "mehmetgon@hotmail.com",
                            FirstName = "Mehmet",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Gön",
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 977, DateTimeKind.Local).AddTicks(6813),
                            Note = "Admin Kullanıcısı",
                            PasswordHash = new byte[] { 48, 49, 57, 50, 48, 50, 51, 97, 55, 98, 98, 100, 55, 51, 50, 53, 48, 53, 49, 54, 102, 48, 54, 57, 100, 102, 49, 56, 98, 53, 48, 48 },
                            Picture = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSX4wVGjMQ37PaO4PdUVEAliSLi8-c2gJ1zvQ&usqp=CAU",
                            RoleId = 1,
                            UserName = "hyperprince"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 977, DateTimeKind.Local).AddTicks(7018),
                            Descreption = "Bu Programın Yazarının arkadaşı",
                            Email = "ilkkanml@outlook.com",
                            FirstName = "Vehbi İlkkan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Memili",
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 977, DateTimeKind.Local).AddTicks(7019),
                            Note = "Moderatör Kullanıcısı",
                            PasswordHash = new byte[] { 52, 97, 99, 98, 52, 98, 99, 50, 50, 52, 97, 99, 98, 98, 101, 51, 99, 50, 98, 102, 100, 99, 97, 97, 51, 57, 97, 52, 51, 50, 52, 101 },
                            Picture = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSX4wVGjMQ37PaO4PdUVEAliSLi8-c2gJ1zvQ&usqp=CAU",
                            RoleId = 2,
                            UserName = "ilkkanml"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 977, DateTimeKind.Local).AddTicks(7025),
                            Descreption = "Bu Programın Yazarının Arkadaşının Eşi",
                            Email = "aym@outlook.com",
                            FirstName = "Açelya",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Yüce Memili",
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 977, DateTimeKind.Local).AddTicks(7026),
                            Note = "Normal Üye Kullanıcısı",
                            PasswordHash = new byte[] { 101, 53, 49, 57, 101, 55, 48, 52, 99, 50, 51, 101, 97, 102, 48, 56, 55, 56, 55, 102, 98, 56, 102, 57, 51, 99, 54, 98, 101, 100, 51, 50 },
                            Picture = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSX4wVGjMQ37PaO4PdUVEAliSLi8-c2gJ1zvQ&usqp=CAU",
                            RoleId = 3,
                            UserName = "aym"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2022, 2, 26, 22, 3, 51, 977, DateTimeKind.Local).AddTicks(7032),
                            Descreption = "Bu Programın Yazarının Oğlu",
                            Email = "mfg@outlook.com",
                            FirstName = "Muhammet Fettah",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Gön",
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2022, 2, 26, 22, 3, 51, 977, DateTimeKind.Local).AddTicks(7033),
                            Note = "Babadan Torpilli Admin",
                            PasswordHash = new byte[] { 52, 56, 49, 56, 102, 49, 50, 98, 97, 99, 49, 52, 52, 53, 56, 51, 48, 54, 51, 54, 52, 57, 97, 100, 52, 57, 100, 101, 100, 52, 54, 54 },
                            Picture = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSX4wVGjMQ37PaO4PdUVEAliSLi8-c2gJ1zvQ&usqp=CAU",
                            RoleId = 1,
                            UserName = "mfg"
                        });
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Article", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entities.Concrete.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.Article", "Articles")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.User", b =>
                {
                    b.HasOne("Blog.Entities.Concrete.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Blog.Entities.Concrete.User", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
